import random
#
# Expandable Database of biscuits by country. 
# Just in case Mike takes his biscuit show on the road. 
# International Man Of Pastry... 
biscuits = {}

biscuits['Italy']  = ["Garibaldi"]

biscuits["UK"] = [
    "Abernethy",
    "Abricot Barquettes",
    "Afghans",
    "All Butter",
    "Animal Biscuits Multireview",
    "Anna's Ginger, Blueberry and Lemon Thins",
    "ANZAC biscuit",
    "Arnott's Gaiety",
    "Arnott's Gingernut",
    "Arnott's Mint Slice",
    "Arnott's Raspberry Shortcake vs Weston's Jam Fancies",
    "Arnott's Spicy Fruit Roll",
    "Asda Fruit Shrewsbury with Lemon Drizzle",
    "Bahlsen Afrika",
    "Bahlsen Crumblys",
    "Bahlsen Hit",
    "Bahlsen Orange Choco Leibniz",
    "Bahlsen PICK UP",
    "Bakers Iced Zoo",
    "Bakers Tennis Biscuits",
    "Bastogne",
    "Bickiepegs",
    "Biscato Spicy and Plain Digesta",
    "Blue Riband",
    "Bodam Carlsbad Spa Wafers",
    "Botham's Tea, Shah Ginger and Ginger Choc Chip biscuits",
    "Bourbon",
    "Brandt Hobbits kernig",
    "Breakaway",
    "Breton Biscuit Super Review",
    "Bronte Selection",
    "Cadbury Oat and Fruit",
    "Cadbury's Choc Brownies and Choc Rings",
    "Cadbury's Fingers",
    "Cafe Bronte Range",
    "Café Noir",
    "Caxton Pink'n'Whites",
    "Chocolate Caramel",
    "Chocolate Chip Cookies Arnotts vs Maryland",
    "Club Milk",
    "Coconut Cream",
    "Cornish Fairings",
    "Crawfords chocolate rings",
    "Custard Cream",
    "Dad's Cookies",
    "Dean's Scottish Preserve Shortbread",
    "Digestive",
    "Dip It",
    "Encorev",
    "Fazer Fasu Pala",
    "Fig Roll",
    "Fox's Brandysnaps",
    "Fox's Butter Crinkle Crunch",
    "Fox's Butter Tea",
    "Fox's Classic",
    "Fox's Creations Bites",
    "Fox's Delicious Cookies",
    "Fox's Mint Echo",
    "Fox's Raisin Cereal Cookies",
    "Fox's Rocky Chocomania Limited Edition",
    "Fox's Simply Goodness Apple and Raspberry Flapjack biscuits",
    "Fox's Sprinkle Crinkle Crunch",
    "Fox's Whipped Creams",
    "Foxs Chocolate Viennese",
    "Foxs Creations",
    "Foxs Ginger Creams",
    "Foxs Party Rings",
    "Fruit Shortcake",
    "Galettes Bretonnes",
    "Garibaldi",
    "Ginger Nut",
    "Girl Scout Cookies",
    "Graham cracker",
    "Green and Blacks Organic Multireview",
    "Griffin's Candy Squiggles",
    "Griffin's vs McVities Ginger Nut",
    "Griffins Chocolate Chippies",
    "Griffins Sultana Pasties",
    "Happy Faces",
    "HobNob",
    "Iced Gems", # are these seriously considered a biscuit??
    "Iced VoVo",
    "Jacob's Mikado",
    "Jacob's Orange Club",
    "Jam Sandwich Creams",
    "Jammie Dodger",
    "Japanese McVities Digestives",
    "Jules Destrooper Almond Thins",
    "Khong Guan creamy chocolate biscuits",
    "Kimberley and Chocolate Kimberley",
    "KitKat",
    "La Paille D'Or",
    "Leafy Pie and Green Tea Pocky",
    "Lidl's Choco Softies",
    "Lincoln",
    "Lotus Caramelised Biscuits",
    "Lu Mikado",
    "Lu Petit Dejeuner",
    "Lyons Fruit Snap Jacks",
    "Malted Milk",
    "Marie",
    "Marks and Spencer Dark Chocolate Ginger",
    "Marks and Spencer Dunking Cookies",
    "Maryland Double Choc Chip Cookie",
    "Maryland Specials Raisin, Oat, Choc Chunk and Maple Syryp Cookies",
    "McVitie's Lyles Creams",
    "McVitie's Milk Chocolate and Orange Digestive",
    "McVities Boaster",
    "McVities Chip 'n' Chunk Cookies",
    "McVities Digestive Cream",
    "McVities Fruitsters",
    "McVities Light Range",
    "McVities Milk Chocolate Digestive",
    "McVities Moments",
    "McVities Taxi",
    "Milk Chocolate and Orange Hobnob",
    "Mint Viscount",
    "Morning Coffee",
    "Nabisco Nutter Butter",
    "Nairns Stem Ginger Wheat Free Biscuits",
    "Naturally Fox's",
    "Noblice",
    "Oreo",
    "Pan European Choc Sandwiches",
    "Parle-G",
    "Penguin",
    "Penguin Splatz",
    "Petit Écolier",
    "Plain Chocolate Gingernut",
    "Polish Jaffa Cakes Multireview",
    "Ponghak Butter",
    "Regal Multireview",
    "Rich Tea",
    "Rich Tea Finger Cream",
    "Ringtons Ginger Snap",
    "Romany Creams",
    "Sainsbury's Ginger Crinkle",
    "Sainsbury's Lemon Thin",
    "Sarah Nelson's Gingerbread",
    "Shortcake",
    "South East Asian Multireview",
    "Strawberry Newton",
    "Tesco's Finest Soft Eating Orange and Cranberry Cookies",
    "Tesco's Organic Fruit Bake Biscuits",
    "Thin Arrowroot",
    "Tim Tam vs Penguin",
    "ToffyPops",
    "Traidcraft Cookies",
    "Tregroes Toffee Waffles",
    "Tunnocks Florida Orange",
    "Tunnocks Tea Cake",
    "Tunnocks Wafer",
    "Vimto and Vanilla Thriller Jammie Dodgers",
    "Wagon Wheel",
    "Waitrose Almond Biscuits",
    "Waitrose Organic Oaten",
    "Weston's Wagon Wheels",
    "Yorkshire Tea",
]


def randomBiscuit(country = "UK"):
    """ 
    Select a biscuit at random from the list of biscuits available by country.
    
    """
    return biscuits[country][ random.randint(0, len(biscuits[country])-1) ]


